version: "3"

services:
  db:
    image: mysql
    container_name: MYSQL
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: 5761929
      MYSQL_DATABASE: poc-bi
    volumes:
      - ./mysql-data:/var/lib/mysql
